# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

"""
BRepFeat module, see official documentation at
https://www.opencascade.com/doc/occt-7.4.0/refman/html/package_brepfeat.html
"""


from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (3, 0, 0):
    new_instancemethod = lambda func, inst, cls: _BRepFeat.SWIG_PyInstanceMethod_New(func)
else:
    from new import instancemethod as new_instancemethod
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_BRepFeat')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_BRepFeat')
    _BRepFeat = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_BRepFeat', [dirname(__file__)])
        except ImportError:
            import _BRepFeat
            return _BRepFeat
        try:
            _mod = imp.load_module('_BRepFeat', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _BRepFeat = swig_import_helper()
    del swig_import_helper
else:
    import _BRepFeat
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_method(set):
    def set_attr(self, name, value):
        if (name == "thisown"):
            return self.this.own(value)
        if hasattr(self, name) or (name == "this"):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr


class SwigPyIterator(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _BRepFeat.delete_SwigPyIterator
    def __iter__(self):
        return self
SwigPyIterator.value = new_instancemethod(_BRepFeat.SwigPyIterator_value, None, SwigPyIterator)
SwigPyIterator.incr = new_instancemethod(_BRepFeat.SwigPyIterator_incr, None, SwigPyIterator)
SwigPyIterator.decr = new_instancemethod(_BRepFeat.SwigPyIterator_decr, None, SwigPyIterator)
SwigPyIterator.distance = new_instancemethod(_BRepFeat.SwigPyIterator_distance, None, SwigPyIterator)
SwigPyIterator.equal = new_instancemethod(_BRepFeat.SwigPyIterator_equal, None, SwigPyIterator)
SwigPyIterator.copy = new_instancemethod(_BRepFeat.SwigPyIterator_copy, None, SwigPyIterator)
SwigPyIterator.next = new_instancemethod(_BRepFeat.SwigPyIterator_next, None, SwigPyIterator)
SwigPyIterator.__next__ = new_instancemethod(_BRepFeat.SwigPyIterator___next__, None, SwigPyIterator)
SwigPyIterator.previous = new_instancemethod(_BRepFeat.SwigPyIterator_previous, None, SwigPyIterator)
SwigPyIterator.advance = new_instancemethod(_BRepFeat.SwigPyIterator_advance, None, SwigPyIterator)
SwigPyIterator.__eq__ = new_instancemethod(_BRepFeat.SwigPyIterator___eq__, None, SwigPyIterator)
SwigPyIterator.__ne__ = new_instancemethod(_BRepFeat.SwigPyIterator___ne__, None, SwigPyIterator)
SwigPyIterator.__iadd__ = new_instancemethod(_BRepFeat.SwigPyIterator___iadd__, None, SwigPyIterator)
SwigPyIterator.__isub__ = new_instancemethod(_BRepFeat.SwigPyIterator___isub__, None, SwigPyIterator)
SwigPyIterator.__add__ = new_instancemethod(_BRepFeat.SwigPyIterator___add__, None, SwigPyIterator)
SwigPyIterator.__sub__ = new_instancemethod(_BRepFeat.SwigPyIterator___sub__, None, SwigPyIterator)
SwigPyIterator_swigregister = _BRepFeat.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)


def _dumps_object(klass):
    """ Overwrite default string output for any wrapped object.
    By default, __repr__ method returns something like:
    <OCC.Core.TopoDS.TopoDS_Shape; proxy of <Swig Object of type 'TopoDS_Shape *' at 0x02BB0758> >
    This is too much verbose.
    We prefer :
    <class 'gp_Pnt'>
    or
    <class 'TopoDS_Shape'>
    """
    klass_name = str(klass.__class__).split(".")[3].split("'")[0]
    repr_string = "<class '" + klass_name + "'"
# for TopoDS_Shape, we also look for the base type
    if klass_name == "TopoDS_Shape":
        if klass.IsNull():
            repr_string += ": Null>"
            return repr_string
        st = klass.ShapeType()
        types = {OCC.Core.TopAbs.TopAbs_VERTEX: "Vertex",
                 OCC.Core.TopAbs.TopAbs_SOLID: "Solid",
                 OCC.Core.TopAbs.TopAbs_EDGE: "Edge",
                 OCC.Core.TopAbs.TopAbs_FACE: "Face",
                 OCC.Core.TopAbs.TopAbs_SHELL: "Shell",
                 OCC.Core.TopAbs.TopAbs_WIRE: "Wire",
                 OCC.Core.TopAbs.TopAbs_COMPOUND: "Compound",
                 OCC.Core.TopAbs.TopAbs_COMPSOLID: "Compsolid"}
        repr_string += "; Type:%s" % types[st]        
    elif hasattr(klass, "IsNull"):
        if klass.IsNull():
            repr_string += "; Null"
    repr_string += ">"
    return repr_string


def process_exception(error: 'Standard_Failure const &', method_name: 'std::string', class_name: 'std::string') -> "void":
    return _BRepFeat.process_exception(error, method_name, class_name)
process_exception = _BRepFeat.process_exception

from six import with_metaclass
import warnings
from OCC.Wrapper.wrapper_utils import Proxy, deprecated

import OCC.Core.Standard
import OCC.Core.NCollection
import OCC.Core.TopoDS
import OCC.Core.Message
import OCC.Core.TopAbs
import OCC.Core.TopLoc
import OCC.Core.gp
import OCC.Core.Geom
import OCC.Core.GeomAbs
import OCC.Core.TColgp
import OCC.Core.TColStd
import OCC.Core.TCollection
import OCC.Core.BOPAlgo
import OCC.Core.TopTools
import OCC.Core.IntTools
import OCC.Core.BRepAdaptor
import OCC.Core.Adaptor3d
import OCC.Core.Adaptor2d
import OCC.Core.Geom2d
import OCC.Core.math
import OCC.Core.GeomAdaptor
import OCC.Core.Geom2dAdaptor
import OCC.Core.Bnd
import OCC.Core.BVH
import OCC.Core.Geom2dHatch
import OCC.Core.IntRes2d
import OCC.Core.HatchGen
import OCC.Core.Geom2dInt
import OCC.Core.IntCurve
import OCC.Core.Extrema
import OCC.Core.Intf
import OCC.Core.GeomAPI
import OCC.Core.Approx
import OCC.Core.AppCont
import OCC.Core.AppParCurves
import OCC.Core.BRepClass3d
import OCC.Core.IntCurveSurface
import OCC.Core.IntSurf
import OCC.Core.IntCurvesFace
import OCC.Core.IntPatch
import OCC.Core.IntAna
import OCC.Core.GeomInt
import OCC.Core.IntImp
import OCC.Core.ApproxInt
import OCC.Core.BOPDS
import OCC.Core.BRepTools
import OCC.Core.BRep
import OCC.Core.Poly
import OCC.Core.TShort
import OCC.Core.BOPTools
import OCC.Core.BRepBuilderAPI
import OCC.Core.TColGeom
import OCC.Core.LocOpe
BRepFeat_NoError = _BRepFeat.BRepFeat_NoError
BRepFeat_InvalidPlacement = _BRepFeat.BRepFeat_InvalidPlacement
BRepFeat_HoleTooLong = _BRepFeat.BRepFeat_HoleTooLong
BRepFeat_OK = _BRepFeat.BRepFeat_OK
BRepFeat_BadDirect = _BRepFeat.BRepFeat_BadDirect
BRepFeat_BadIntersect = _BRepFeat.BRepFeat_BadIntersect
BRepFeat_EmptyBaryCurve = _BRepFeat.BRepFeat_EmptyBaryCurve
BRepFeat_EmptyCutResult = _BRepFeat.BRepFeat_EmptyCutResult
BRepFeat_FalseSide = _BRepFeat.BRepFeat_FalseSide
BRepFeat_IncDirection = _BRepFeat.BRepFeat_IncDirection
BRepFeat_IncSlidFace = _BRepFeat.BRepFeat_IncSlidFace
BRepFeat_IncParameter = _BRepFeat.BRepFeat_IncParameter
BRepFeat_IncTypes = _BRepFeat.BRepFeat_IncTypes
BRepFeat_IntervalOverlap = _BRepFeat.BRepFeat_IntervalOverlap
BRepFeat_InvFirstShape = _BRepFeat.BRepFeat_InvFirstShape
BRepFeat_InvOption = _BRepFeat.BRepFeat_InvOption
BRepFeat_InvShape = _BRepFeat.BRepFeat_InvShape
BRepFeat_LocOpeNotDone = _BRepFeat.BRepFeat_LocOpeNotDone
BRepFeat_LocOpeInvNotDone = _BRepFeat.BRepFeat_LocOpeInvNotDone
BRepFeat_NoExtFace = _BRepFeat.BRepFeat_NoExtFace
BRepFeat_NoFaceProf = _BRepFeat.BRepFeat_NoFaceProf
BRepFeat_NoGluer = _BRepFeat.BRepFeat_NoGluer
BRepFeat_NoIntersectF = _BRepFeat.BRepFeat_NoIntersectF
BRepFeat_NoIntersectU = _BRepFeat.BRepFeat_NoIntersectU
BRepFeat_NoParts = _BRepFeat.BRepFeat_NoParts
BRepFeat_NoProjPt = _BRepFeat.BRepFeat_NoProjPt
BRepFeat_NotInitialized = _BRepFeat.BRepFeat_NotInitialized
BRepFeat_NotYetImplemented = _BRepFeat.BRepFeat_NotYetImplemented
BRepFeat_NullRealTool = _BRepFeat.BRepFeat_NullRealTool
BRepFeat_NullToolF = _BRepFeat.BRepFeat_NullToolF
BRepFeat_NullToolU = _BRepFeat.BRepFeat_NullToolU
BRepFeat_NoSelection = _BRepFeat.BRepFeat_NoSelection
BRepFeat_SelectionFU = _BRepFeat.BRepFeat_SelectionFU
BRepFeat_SelectionU = _BRepFeat.BRepFeat_SelectionU
BRepFeat_SelectionSh = _BRepFeat.BRepFeat_SelectionSh
BRepFeat_SelectionShU = _BRepFeat.BRepFeat_SelectionShU
class brepfeat(object):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def Barycenter(*args) -> "void":
        """
        :param S:
        	:type S: TopoDS_Shape
        	:param Pt:
        	:type Pt: gp_Pnt
        	:rtype: void
        """
        return _BRepFeat.brepfeat_Barycenter(*args)

    Barycenter = staticmethod(Barycenter)

    def FaceUntil(*args) -> "void":
        """
        :param S:
        	:type S: TopoDS_Shape
        	:param F:
        	:type F: TopoDS_Face
        	:rtype: void
        """
        return _BRepFeat.brepfeat_FaceUntil(*args)

    FaceUntil = staticmethod(FaceUntil)

    def IsInside(*args) -> "Standard_Boolean":
        """
        :param F1:
        	:type F1: TopoDS_Face
        	:param F2:
        	:type F2: TopoDS_Face
        	:rtype: bool
        """
        return _BRepFeat.brepfeat_IsInside(*args)

    IsInside = staticmethod(IsInside)

    def ParametricBarycenter(*args) -> "Standard_Real":
        """
        :param S:
        	:type S: TopoDS_Shape
        	:param C:
        	:type C: Geom_Curve
        	:rtype: float
        """
        return _BRepFeat.brepfeat_ParametricBarycenter(*args)

    ParametricBarycenter = staticmethod(ParametricBarycenter)

    def ParametricMinMax(*args) -> "Standard_Real &, Standard_Real &, Standard_Real &, Standard_Real &, Standard_Boolean &":
        """
        * Ori = True taking account the orientation
        	:param S:
        	:type S: TopoDS_Shape
        	:param C:
        	:type C: Geom_Curve
        	:param prmin:
        	:type prmin: float
        	:param prmax:
        	:type prmax: float
        	:param prbmin:
        	:type prbmin: float
        	:param prbmax:
        	:type prbmax: float
        	:param flag:
        	:type flag: bool
        	:param Ori: default value is Standard_False
        	:type Ori: bool
        	:rtype: void
        """
        return _BRepFeat.brepfeat_ParametricMinMax(*args)

    ParametricMinMax = staticmethod(ParametricMinMax)

    def Print(*args) -> "Standard_OStream &":
        """
        * Prints the Error description of the State <St> as a String on the Stream <S> and returns <S>.
        	:param SE:
        	:type SE: BRepFeat_StatusError
        	:param S:
        	:type S: Standard_OStream
        	:rtype: Standard_OStream
        """
        return _BRepFeat.brepfeat_Print(*args)

    Print = staticmethod(Print)

    def SampleEdges(*args) -> "void":
        """
        :param S:
        	:type S: TopoDS_Shape
        	:param Pt:
        	:type Pt: TColgp_SequenceOfPnt
        	:rtype: void
        """
        return _BRepFeat.brepfeat_SampleEdges(*args)

    SampleEdges = staticmethod(SampleEdges)

    def Tool(*args) -> "TopoDS_Solid":
        """
        :param SRef:
        	:type SRef: TopoDS_Shape
        	:param Fac:
        	:type Fac: TopoDS_Face
        	:param Orf:
        	:type Orf: TopAbs_Orientation
        	:rtype: TopoDS_Solid
        """
        return _BRepFeat.brepfeat_Tool(*args)

    Tool = staticmethod(Tool)

    __repr__ = _dumps_object


    def __init__(self):
        _BRepFeat.brepfeat_swiginit(self, _BRepFeat.new_brepfeat())
    __swig_destroy__ = _BRepFeat.delete_brepfeat
brepfeat_swigregister = _BRepFeat.brepfeat_swigregister
brepfeat_swigregister(brepfeat)

def brepfeat_Barycenter(*args) -> "void":
    """
    :param S:
    	:type S: TopoDS_Shape
    	:param Pt:
    	:type Pt: gp_Pnt
    	:rtype: void
    """
    return _BRepFeat.brepfeat_Barycenter(*args)

def brepfeat_FaceUntil(*args) -> "void":
    """
    :param S:
    	:type S: TopoDS_Shape
    	:param F:
    	:type F: TopoDS_Face
    	:rtype: void
    """
    return _BRepFeat.brepfeat_FaceUntil(*args)

def brepfeat_IsInside(*args) -> "Standard_Boolean":
    """
    :param F1:
    	:type F1: TopoDS_Face
    	:param F2:
    	:type F2: TopoDS_Face
    	:rtype: bool
    """
    return _BRepFeat.brepfeat_IsInside(*args)

def brepfeat_ParametricBarycenter(*args) -> "Standard_Real":
    """
    :param S:
    	:type S: TopoDS_Shape
    	:param C:
    	:type C: Geom_Curve
    	:rtype: float
    """
    return _BRepFeat.brepfeat_ParametricBarycenter(*args)

def brepfeat_ParametricMinMax(*args) -> "Standard_Real &, Standard_Real &, Standard_Real &, Standard_Real &, Standard_Boolean &":
    """
    * Ori = True taking account the orientation
    	:param S:
    	:type S: TopoDS_Shape
    	:param C:
    	:type C: Geom_Curve
    	:param prmin:
    	:type prmin: float
    	:param prmax:
    	:type prmax: float
    	:param prbmin:
    	:type prbmin: float
    	:param prbmax:
    	:type prbmax: float
    	:param flag:
    	:type flag: bool
    	:param Ori: default value is Standard_False
    	:type Ori: bool
    	:rtype: void
    """
    return _BRepFeat.brepfeat_ParametricMinMax(*args)

def brepfeat_Print(*args) -> "Standard_OStream &":
    """
    * Prints the Error description of the State <St> as a String on the Stream <S> and returns <S>.
    	:param SE:
    	:type SE: BRepFeat_StatusError
    	:param S:
    	:type S: Standard_OStream
    	:rtype: Standard_OStream
    """
    return _BRepFeat.brepfeat_Print(*args)

def brepfeat_SampleEdges(*args) -> "void":
    """
    :param S:
    	:type S: TopoDS_Shape
    	:param Pt:
    	:type Pt: TColgp_SequenceOfPnt
    	:rtype: void
    """
    return _BRepFeat.brepfeat_SampleEdges(*args)

def brepfeat_Tool(*args) -> "TopoDS_Solid":
    """
    :param SRef:
    	:type SRef: TopoDS_Shape
    	:param Fac:
    	:type Fac: TopoDS_Face
    	:param Orf:
    	:type Orf: TopAbs_Orientation
    	:rtype: TopoDS_Solid
    """
    return _BRepFeat.brepfeat_Tool(*args)

class BRepFeat_Builder(OCC.Core.BOPAlgo.BOPAlgo_BOP):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """:rtype: None"""
        _BRepFeat.BRepFeat_Builder_swiginit(self, _BRepFeat.new_BRepFeat_Builder(*args))

    def CheckSolidImages(self, *args) -> "void":
        """
        * Collects the images of the object, that contains in the images of the tool.
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_Builder_CheckSolidImages(self, *args)


    def FillRemoved(self, *args) -> "void":
        """
        * Collects the removed parts of the tool into myRemoved map.
        	:rtype: None
        * Adds the shape S and its sub-shapes into myRemoved map.
        	:param theS:
        	:type theS: TopoDS_Shape
        	:param theM:
        	:type theM: TopTools_MapOfShape
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_Builder_FillRemoved(self, *args)


    def Init(self, *args) -> "void":
        """
        * Initialyzes the object of local boolean operation.
        	:param theShape:
        	:type theShape: TopoDS_Shape
        	:rtype: None
        * Initialyzes the arguments of local boolean operation.
        	:param theShape:
        	:type theShape: TopoDS_Shape
        	:param theTool:
        	:type theTool: TopoDS_Shape
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_Builder_Init(self, *args)


    def KeepPart(self, *args) -> "void":
        """
        * Adds shape theS and all its sub-shapes into myShapes map.
        	:param theS:
        	:type theS: TopoDS_Shape
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_Builder_KeepPart(self, *args)


    def KeepParts(self, *args) -> "void":
        """
        * Initialyzes parts of the tool for second step of algorithm. Collects shapes and all sub-shapes into myShapes map.
        	:param theIm:
        	:type theIm: TopTools_ListOfShape
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_Builder_KeepParts(self, *args)


    def PartsOfTool(self, *args) -> "void":
        """
        * Collects parts of the tool.
        	:param theLT:
        	:type theLT: TopTools_ListOfShape
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_Builder_PartsOfTool(self, *args)


    def PerformResult(self, *args) -> "void":
        """
        * Main function to build the result of the local operation required.
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_Builder_PerformResult(self, *args)


    def RebuildEdge(self, *args) -> "void":
        """
        * Rebuilds edges in accordance with the kept parts of the tool.
        	:param theE:
        	:type theE: TopoDS_Shape
        	:param theF:
        	:type theF: TopoDS_Face
        	:param theME:
        	:type theME: TopTools_MapOfShape
        	:param aLEIm:
        	:type aLEIm: TopTools_ListOfShape
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_Builder_RebuildEdge(self, *args)


    def RebuildFaces(self, *args) -> "void":
        """
        * Rebuilds faces in accordance with the kept parts of the tool.
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_Builder_RebuildFaces(self, *args)


    def SetOperation(self, *args) -> "void":
        """
        * Sets the operation of local boolean operation. If theFuse = 0 than the operation is CUT, otherwise FUSE.
        	:param theFuse:
        	:type theFuse: int
        	:rtype: None
        * Sets the operation of local boolean operation. If theFlag = True it means that no selection of parts of the tool is needed, t.e. no second part. In that case if theFuse = 0 than operation is COMMON, otherwise CUT21. If theFlag = False SetOperation(theFuse) function is called.
        	:param theFuse:
        	:type theFuse: int
        	:param theFlag:
        	:type theFlag: bool
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_Builder_SetOperation(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _BRepFeat.delete_BRepFeat_Builder
BRepFeat_Builder.CheckSolidImages = new_instancemethod(_BRepFeat.BRepFeat_Builder_CheckSolidImages, None, BRepFeat_Builder)
BRepFeat_Builder.FillRemoved = new_instancemethod(_BRepFeat.BRepFeat_Builder_FillRemoved, None, BRepFeat_Builder)
BRepFeat_Builder.Init = new_instancemethod(_BRepFeat.BRepFeat_Builder_Init, None, BRepFeat_Builder)
BRepFeat_Builder.KeepPart = new_instancemethod(_BRepFeat.BRepFeat_Builder_KeepPart, None, BRepFeat_Builder)
BRepFeat_Builder.KeepParts = new_instancemethod(_BRepFeat.BRepFeat_Builder_KeepParts, None, BRepFeat_Builder)
BRepFeat_Builder.PartsOfTool = new_instancemethod(_BRepFeat.BRepFeat_Builder_PartsOfTool, None, BRepFeat_Builder)
BRepFeat_Builder.PerformResult = new_instancemethod(_BRepFeat.BRepFeat_Builder_PerformResult, None, BRepFeat_Builder)
BRepFeat_Builder.RebuildEdge = new_instancemethod(_BRepFeat.BRepFeat_Builder_RebuildEdge, None, BRepFeat_Builder)
BRepFeat_Builder.RebuildFaces = new_instancemethod(_BRepFeat.BRepFeat_Builder_RebuildFaces, None, BRepFeat_Builder)
BRepFeat_Builder.SetOperation = new_instancemethod(_BRepFeat.BRepFeat_Builder_SetOperation, None, BRepFeat_Builder)
BRepFeat_Builder_swigregister = _BRepFeat.BRepFeat_Builder_swigregister
BRepFeat_Builder_swigregister(BRepFeat_Builder)

class BRepFeat_Form(OCC.Core.BRepBuilderAPI.BRepBuilderAPI_MakeShape):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def BarycCurve(self, *args) -> "opencascade::handle< Geom_Curve >":
        """:rtype: opencascade::handle<Geom_Curve>"""
        return _BRepFeat.BRepFeat_Form_BarycCurve(self, *args)


    def BasisShapeValid(self, *args) -> "void":
        """
        * Initializes the topological construction if the basis shape is present.
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_Form_BasisShapeValid(self, *args)


    def CurrentStatusError(self, *args) -> "BRepFeat_StatusError":
        """:rtype: BRepFeat_StatusError"""
        return _BRepFeat.BRepFeat_Form_CurrentStatusError(self, *args)


    def Curves(self, *args) -> "void":
        """
        :param S:
        	:type S: TColGeom_SequenceOfCurve
        	:rtype: void
        """
        return _BRepFeat.BRepFeat_Form_Curves(self, *args)


    def FirstShape(self, *args) -> "TopTools_ListOfShape const &":
        """
        * Returns the list of shapes created at the bottom of the created form. It may be an empty list.
        	:rtype: TopTools_ListOfShape
        """
        return _BRepFeat.BRepFeat_Form_FirstShape(self, *args)


    def GeneratedShapeValid(self, *args) -> "void":
        """
        * Initializes the topological construction if the generated shape S is present.
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_Form_GeneratedShapeValid(self, *args)


    def GluedFacesValid(self, *args) -> "void":
        """
        * Initializes the topological construction if the glued face is present.
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_Form_GluedFacesValid(self, *args)


    def LastShape(self, *args) -> "TopTools_ListOfShape const &":
        """
        * Returns the list of shapes created at the top of the created form. It may be an empty list.
        	:rtype: TopTools_ListOfShape
        """
        return _BRepFeat.BRepFeat_Form_LastShape(self, *args)


    def NewEdges(self, *args) -> "TopTools_ListOfShape const &":
        """
        * Returns a list of the limiting and glueing edges generated by the feature. These edges did not originally exist in the basis shape. The list provides the information necessary for subsequent addition of fillets. It may be an empty list.
        	:rtype: TopTools_ListOfShape
        """
        return _BRepFeat.BRepFeat_Form_NewEdges(self, *args)


    def PerfSelectionValid(self, *args) -> "void":
        """
        * Initializes the topological construction if the selected face is present.
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_Form_PerfSelectionValid(self, *args)


    def ShapeFromValid(self, *args) -> "void":
        """
        * Initializes the topological construction if the shape is present from the specified integer on.
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_Form_ShapeFromValid(self, *args)


    def ShapeUntilValid(self, *args) -> "void":
        """
        * Initializes the topological construction if the shape is present until the specified integer.
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_Form_ShapeUntilValid(self, *args)


    def SketchFaceValid(self, *args) -> "void":
        """
        * Initializes the topological construction if the sketch face is present. If the sketch face is inside the basis shape, local operations such as glueing can be performed.
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_Form_SketchFaceValid(self, *args)


    def TgtEdges(self, *args) -> "TopTools_ListOfShape const &":
        """
        * Returns a list of the tangent edges among the limiting and glueing edges generated by the feature. These edges did not originally exist in the basis shape and are tangent to the face against which the feature is built. The list provides the information necessary for subsequent addition of fillets. It may be an empty list. If an edge is tangent, no fillet is possible, and the edge must subsequently be removed if you want to add a fillet.
        	:rtype: TopTools_ListOfShape
        """
        return _BRepFeat.BRepFeat_Form_TgtEdges(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _BRepFeat.delete_BRepFeat_Form
BRepFeat_Form.BarycCurve = new_instancemethod(_BRepFeat.BRepFeat_Form_BarycCurve, None, BRepFeat_Form)
BRepFeat_Form.BasisShapeValid = new_instancemethod(_BRepFeat.BRepFeat_Form_BasisShapeValid, None, BRepFeat_Form)
BRepFeat_Form.CurrentStatusError = new_instancemethod(_BRepFeat.BRepFeat_Form_CurrentStatusError, None, BRepFeat_Form)
BRepFeat_Form.Curves = new_instancemethod(_BRepFeat.BRepFeat_Form_Curves, None, BRepFeat_Form)
BRepFeat_Form.FirstShape = new_instancemethod(_BRepFeat.BRepFeat_Form_FirstShape, None, BRepFeat_Form)
BRepFeat_Form.GeneratedShapeValid = new_instancemethod(_BRepFeat.BRepFeat_Form_GeneratedShapeValid, None, BRepFeat_Form)
BRepFeat_Form.GluedFacesValid = new_instancemethod(_BRepFeat.BRepFeat_Form_GluedFacesValid, None, BRepFeat_Form)
BRepFeat_Form.LastShape = new_instancemethod(_BRepFeat.BRepFeat_Form_LastShape, None, BRepFeat_Form)
BRepFeat_Form.NewEdges = new_instancemethod(_BRepFeat.BRepFeat_Form_NewEdges, None, BRepFeat_Form)
BRepFeat_Form.PerfSelectionValid = new_instancemethod(_BRepFeat.BRepFeat_Form_PerfSelectionValid, None, BRepFeat_Form)
BRepFeat_Form.ShapeFromValid = new_instancemethod(_BRepFeat.BRepFeat_Form_ShapeFromValid, None, BRepFeat_Form)
BRepFeat_Form.ShapeUntilValid = new_instancemethod(_BRepFeat.BRepFeat_Form_ShapeUntilValid, None, BRepFeat_Form)
BRepFeat_Form.SketchFaceValid = new_instancemethod(_BRepFeat.BRepFeat_Form_SketchFaceValid, None, BRepFeat_Form)
BRepFeat_Form.TgtEdges = new_instancemethod(_BRepFeat.BRepFeat_Form_TgtEdges, None, BRepFeat_Form)
BRepFeat_Form_swigregister = _BRepFeat.BRepFeat_Form_swigregister
BRepFeat_Form_swigregister(BRepFeat_Form)

class BRepFeat_Gluer(OCC.Core.BRepBuilderAPI.BRepBuilderAPI_MakeShape):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Initializes an empty constructor
        	:rtype: None
        * Initializes the shapes to be glued, the new shape Snew and the basis shape Sbase.
        	:param Snew:
        	:type Snew: TopoDS_Shape
        	:param Sbase:
        	:type Sbase: TopoDS_Shape
        	:rtype: None
        """
        _BRepFeat.BRepFeat_Gluer_swiginit(self, _BRepFeat.new_BRepFeat_Gluer(*args))

    def BasisShape(self, *args) -> "TopoDS_Shape const":
        """
        * Returns the basis shape of the compound shape.
        	:rtype: TopoDS_Shape
        """
        return _BRepFeat.BRepFeat_Gluer_BasisShape(self, *args)


    def Bind(self, *args) -> "void":
        """
        * Defines a contact between Fnew on the new shape Snew and Fbase on the basis shape Sbase. Informs other methods that Fnew in the new shape Snew is connected to the face Fbase in the basis shape Sbase. The contact faces of the glued shape must not have parts outside the contact faces of the basis shape. This indicates that glueing is possible.
        	:param Fnew:
        	:type Fnew: TopoDS_Face
        	:param Fbase:
        	:type Fbase: TopoDS_Face
        	:rtype: None
        * nforms other methods that the edge Enew in the new shape is the same as the edge Ebase in the basis shape and is therefore attached to the basis shape. This indicates that glueing is possible.
        	:param Enew:
        	:type Enew: TopoDS_Edge
        	:param Ebase:
        	:type Ebase: TopoDS_Edge
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_Gluer_Bind(self, *args)


    def GluedShape(self, *args) -> "TopoDS_Shape const":
        """
        * Returns the resulting compound shape.
        	:rtype: TopoDS_Shape
        """
        return _BRepFeat.BRepFeat_Gluer_GluedShape(self, *args)


    def Init(self, *args) -> "void":
        """
        * Initializes the new shape Snew and the basis shape Sbase for the local glueing operation.
        	:param Snew:
        	:type Snew: TopoDS_Shape
        	:param Sbase:
        	:type Sbase: TopoDS_Shape
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_Gluer_Init(self, *args)


    def OpeType(self, *args) -> "LocOpe_Operation":
        """
        * Determine which operation type to use glueing or sliding.
        	:rtype: LocOpe_Operation
        """
        return _BRepFeat.BRepFeat_Gluer_OpeType(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _BRepFeat.delete_BRepFeat_Gluer
BRepFeat_Gluer.BasisShape = new_instancemethod(_BRepFeat.BRepFeat_Gluer_BasisShape, None, BRepFeat_Gluer)
BRepFeat_Gluer.Bind = new_instancemethod(_BRepFeat.BRepFeat_Gluer_Bind, None, BRepFeat_Gluer)
BRepFeat_Gluer.GluedShape = new_instancemethod(_BRepFeat.BRepFeat_Gluer_GluedShape, None, BRepFeat_Gluer)
BRepFeat_Gluer.Init = new_instancemethod(_BRepFeat.BRepFeat_Gluer_Init, None, BRepFeat_Gluer)
BRepFeat_Gluer.OpeType = new_instancemethod(_BRepFeat.BRepFeat_Gluer_OpeType, None, BRepFeat_Gluer)
BRepFeat_Gluer_swigregister = _BRepFeat.BRepFeat_Gluer_swigregister
BRepFeat_Gluer_swigregister(BRepFeat_Gluer)

class BRepFeat_RibSlot(OCC.Core.BRepBuilderAPI.BRepBuilderAPI_MakeShape):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr

    def ChoiceOfFaces(*args) -> "TopoDS_Face":
        """
        :param faces:
        	:type faces: TopTools_ListOfShape
        	:param cc:
        	:type cc: Geom_Curve
        	:param par:
        	:type par: float
        	:param bnd:
        	:type bnd: float
        	:param Pln:
        	:type Pln: Geom_Plane
        	:rtype: TopoDS_Face
        """
        return _BRepFeat.BRepFeat_RibSlot_ChoiceOfFaces(*args)

    ChoiceOfFaces = staticmethod(ChoiceOfFaces)

    def CurrentStatusError(self, *args) -> "BRepFeat_StatusError":
        """:rtype: BRepFeat_StatusError"""
        return _BRepFeat.BRepFeat_RibSlot_CurrentStatusError(self, *args)


    def FacesForDraft(self, *args) -> "TopTools_ListOfShape const &":
        """
        * Returns a list of the limiting and glueing faces generated by the feature. These faces did not originally exist in the basis shape. The list provides the information necessary for subsequent addition of a draft to a face. It may be an empty list. If a face has tangent edges, no draft is possible, and the tangent edges must subsequently be removed if you want to add a draft to the face.
        	:rtype: TopTools_ListOfShape
        """
        return _BRepFeat.BRepFeat_RibSlot_FacesForDraft(self, *args)


    def FirstShape(self, *args) -> "TopTools_ListOfShape const &":
        """
        * Returns the list of shapes created at the bottom of the created form. It may be an empty list.
        	:rtype: TopTools_ListOfShape
        """
        return _BRepFeat.BRepFeat_RibSlot_FirstShape(self, *args)


    def IntPar(*args) -> "Standard_Real":
        """
        :param C:
        	:type C: Geom_Curve
        	:param P:
        	:type P: gp_Pnt
        	:rtype: float
        """
        return _BRepFeat.BRepFeat_RibSlot_IntPar(*args)

    IntPar = staticmethod(IntPar)

    def LastShape(self, *args) -> "TopTools_ListOfShape const &":
        """
        * Returns the list of shapes created at the top of the created form. It may be an empty list.
        	:rtype: TopTools_ListOfShape
        """
        return _BRepFeat.BRepFeat_RibSlot_LastShape(self, *args)


    def NewEdges(self, *args) -> "TopTools_ListOfShape const &":
        """
        * Returns a list of the limiting and glueing edges generated by the feature. These edges did not originally exist in the basis shape. The list provides the information necessary for subsequent addition of fillets. It may be an empty list.
        	:rtype: TopTools_ListOfShape
        """
        return _BRepFeat.BRepFeat_RibSlot_NewEdges(self, *args)


    def TgtEdges(self, *args) -> "TopTools_ListOfShape const &":
        """
        * Returns a list of the tangent edges among the limiting and glueing edges generated by the feature. These edges did not originally exist in the basis shape and are tangent to the face against which the feature is built. The list provides the information necessary for subsequent addition of fillets. It may be an empty list. If an edge is tangent, no fillet is possible, and the edge must subsequently be removed if you want to add a fillet.
        	:rtype: TopTools_ListOfShape
        """
        return _BRepFeat.BRepFeat_RibSlot_TgtEdges(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _BRepFeat.delete_BRepFeat_RibSlot
BRepFeat_RibSlot.CurrentStatusError = new_instancemethod(_BRepFeat.BRepFeat_RibSlot_CurrentStatusError, None, BRepFeat_RibSlot)
BRepFeat_RibSlot.FacesForDraft = new_instancemethod(_BRepFeat.BRepFeat_RibSlot_FacesForDraft, None, BRepFeat_RibSlot)
BRepFeat_RibSlot.FirstShape = new_instancemethod(_BRepFeat.BRepFeat_RibSlot_FirstShape, None, BRepFeat_RibSlot)
BRepFeat_RibSlot.LastShape = new_instancemethod(_BRepFeat.BRepFeat_RibSlot_LastShape, None, BRepFeat_RibSlot)
BRepFeat_RibSlot.NewEdges = new_instancemethod(_BRepFeat.BRepFeat_RibSlot_NewEdges, None, BRepFeat_RibSlot)
BRepFeat_RibSlot.TgtEdges = new_instancemethod(_BRepFeat.BRepFeat_RibSlot_TgtEdges, None, BRepFeat_RibSlot)
BRepFeat_RibSlot_swigregister = _BRepFeat.BRepFeat_RibSlot_swigregister
BRepFeat_RibSlot_swigregister(BRepFeat_RibSlot)

def BRepFeat_RibSlot_ChoiceOfFaces(*args) -> "TopoDS_Face":
    """
    :param faces:
    	:type faces: TopTools_ListOfShape
    	:param cc:
    	:type cc: Geom_Curve
    	:param par:
    	:type par: float
    	:param bnd:
    	:type bnd: float
    	:param Pln:
    	:type Pln: Geom_Plane
    	:rtype: TopoDS_Face
    """
    return _BRepFeat.BRepFeat_RibSlot_ChoiceOfFaces(*args)

def BRepFeat_RibSlot_IntPar(*args) -> "Standard_Real":
    """
    :param C:
    	:type C: Geom_Curve
    	:param P:
    	:type P: gp_Pnt
    	:rtype: float
    """
    return _BRepFeat.BRepFeat_RibSlot_IntPar(*args)

class BRepFeat_SplitShape(OCC.Core.BRepBuilderAPI.BRepBuilderAPI_MakeShape):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def Add(self, *args) -> "void":
        """
        * Add splitting edges or wires for whole initial shape withot additional specification edge->face, edge->edge This method puts edge on the corresponding faces from initial shape
        	:param theEdges:
        	:type theEdges: TopTools_SequenceOfShape
        	:rtype: bool
        * Adds the wire <W> on the face <F>. Raises NoSuchObject if <F> does not belong to the original shape.
        	:param W:
        	:type W: TopoDS_Wire
        	:param F:
        	:type F: TopoDS_Face
        	:rtype: None
        * Adds the edge <E> on the face <F>.
        	:param E:
        	:type E: TopoDS_Edge
        	:param F:
        	:type F: TopoDS_Face
        	:rtype: None
        * Adds the compound <Comp> on the face <F>. The compound <Comp> must consist of edges lying on the face <F>. If edges are geometrically connected, they must be connected topologically, i.e. they must share common vertices. //! Raises NoSuchObject if <F> does not belong to the original shape.
        	:param Comp:
        	:type Comp: TopoDS_Compound
        	:param F:
        	:type F: TopoDS_Face
        	:rtype: None
        * Adds the edge <E> on the existing edge <EOn>.
        	:param E:
        	:type E: TopoDS_Edge
        	:param EOn:
        	:type EOn: TopoDS_Edge
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_SplitShape_Add(self, *args)


    def __init__(self, *args):
        """
        * Empty constructor
        	:rtype: None
        * Creates the process with the shape <S>.
        	:param S:
        	:type S: TopoDS_Shape
        	:rtype: None
        """
        _BRepFeat.BRepFeat_SplitShape_swiginit(self, _BRepFeat.new_BRepFeat_SplitShape(*args))

    def DirectLeft(self, *args) -> "TopTools_ListOfShape const &":
        """
        * Returns the faces which are the left of the projected wires.
        	:rtype: TopTools_ListOfShape
        """
        return _BRepFeat.BRepFeat_SplitShape_DirectLeft(self, *args)


    def Init(self, *args) -> "void":
        """
        * Initializes the process on the shape <S>.
        	:param S:
        	:type S: TopoDS_Shape
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_SplitShape_Init(self, *args)


    def Left(self, *args) -> "TopTools_ListOfShape const &":
        """
        * Returns the faces of the 'left' part on the shape. (It is build from DirectLeft, with the faces connected to this set, and so on...). Raises NotDone if IsDone returns <Standard_False>.
        	:rtype: TopTools_ListOfShape
        """
        return _BRepFeat.BRepFeat_SplitShape_Left(self, *args)


    def SetCheckInterior(self, *args) -> "void":
        """
        * Set the flag of check internal intersections default value is True (to check)
        	:param ToCheckInterior:
        	:type ToCheckInterior: bool
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_SplitShape_SetCheckInterior(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _BRepFeat.delete_BRepFeat_SplitShape
BRepFeat_SplitShape.Add = new_instancemethod(_BRepFeat.BRepFeat_SplitShape_Add, None, BRepFeat_SplitShape)
BRepFeat_SplitShape.DirectLeft = new_instancemethod(_BRepFeat.BRepFeat_SplitShape_DirectLeft, None, BRepFeat_SplitShape)
BRepFeat_SplitShape.Init = new_instancemethod(_BRepFeat.BRepFeat_SplitShape_Init, None, BRepFeat_SplitShape)
BRepFeat_SplitShape.Left = new_instancemethod(_BRepFeat.BRepFeat_SplitShape_Left, None, BRepFeat_SplitShape)
BRepFeat_SplitShape.SetCheckInterior = new_instancemethod(_BRepFeat.BRepFeat_SplitShape_SetCheckInterior, None, BRepFeat_SplitShape)
BRepFeat_SplitShape_swigregister = _BRepFeat.BRepFeat_SplitShape_swigregister
BRepFeat_SplitShape_swigregister(BRepFeat_SplitShape)

class BRepFeat_MakeCylindricalHole(BRepFeat_Builder):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def __init__(self, *args):
        """
        * Empty constructor.
        	:rtype: None
        """
        _BRepFeat.BRepFeat_MakeCylindricalHole_swiginit(self, _BRepFeat.new_BRepFeat_MakeCylindricalHole(*args))

    def Build(self, *args) -> "void":
        """
        * Builds the resulting shape (redefined from MakeShape). Invalidates the given parts of tools if any, and performs the result of the local operation.
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeCylindricalHole_Build(self, *args)


    def Init(self, *args) -> "void":
        """
        * Sets the axis of the hole(s).
        	:param Axis:
        	:type Axis: gp_Ax1
        	:rtype: None
        * Sets the shape and axis on which hole(s) will be performed.
        	:param S:
        	:type S: TopoDS_Shape
        	:param Axis:
        	:type Axis: gp_Ax1
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeCylindricalHole_Init(self, *args)


    def Perform(self, *args) -> "void":
        """
        * Performs every holes of radius <Radius>. This command has the same effect as a cut operation with an infinite cylinder defined by the given axis and <Radius>.
        	:param Radius:
        	:type Radius: float
        	:rtype: None
        * Performs evry hole of radius <Radius> located between PFrom and PTo on the given axis. If <WithControl> is set to Standard_False no control are done on the resulting shape after the operation is performed.
        	:param Radius:
        	:type Radius: float
        	:param PFrom:
        	:type PFrom: float
        	:param PTo:
        	:type PTo: float
        	:param WithControl: default value is Standard_True
        	:type WithControl: bool
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeCylindricalHole_Perform(self, *args)


    def PerformBlind(self, *args) -> "void":
        """
        * Performs a blind hole of radius <Radius> and length <Length>. The length is measured from the origin of the given axis. If <WithControl> is set to Standard_False no control are done after the operation is performed.
        	:param Radius:
        	:type Radius: float
        	:param Length:
        	:type Length: float
        	:param WithControl: default value is Standard_True
        	:type WithControl: bool
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeCylindricalHole_PerformBlind(self, *args)


    def PerformThruNext(self, *args) -> "void":
        """
        * Performs the first hole of radius <Radius>, in the direction of the defined axis. First hole signify first encountered after the origin of the axis. If <WithControl> is set to Standard_False no control are done on the resulting shape after the operation is performed.
        	:param Radius:
        	:type Radius: float
        	:param WithControl: default value is Standard_True
        	:type WithControl: bool
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeCylindricalHole_PerformThruNext(self, *args)


    def PerformUntilEnd(self, *args) -> "void":
        """
        * Performs evry holes of radius <Radius> located after the origin of the given axis. If <WithControl> is set to Standard_False no control are done on the resulting shape after the operation is performed.
        	:param Radius:
        	:type Radius: float
        	:param WithControl: default value is Standard_True
        	:type WithControl: bool
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeCylindricalHole_PerformUntilEnd(self, *args)


    def Status(self, *args) -> "BRepFeat_Status":
        """
        * Returns the status after a hole is performed.
        	:rtype: BRepFeat_Status
        """
        return _BRepFeat.BRepFeat_MakeCylindricalHole_Status(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _BRepFeat.delete_BRepFeat_MakeCylindricalHole
BRepFeat_MakeCylindricalHole.Build = new_instancemethod(_BRepFeat.BRepFeat_MakeCylindricalHole_Build, None, BRepFeat_MakeCylindricalHole)
BRepFeat_MakeCylindricalHole.Init = new_instancemethod(_BRepFeat.BRepFeat_MakeCylindricalHole_Init, None, BRepFeat_MakeCylindricalHole)
BRepFeat_MakeCylindricalHole.Perform = new_instancemethod(_BRepFeat.BRepFeat_MakeCylindricalHole_Perform, None, BRepFeat_MakeCylindricalHole)
BRepFeat_MakeCylindricalHole.PerformBlind = new_instancemethod(_BRepFeat.BRepFeat_MakeCylindricalHole_PerformBlind, None, BRepFeat_MakeCylindricalHole)
BRepFeat_MakeCylindricalHole.PerformThruNext = new_instancemethod(_BRepFeat.BRepFeat_MakeCylindricalHole_PerformThruNext, None, BRepFeat_MakeCylindricalHole)
BRepFeat_MakeCylindricalHole.PerformUntilEnd = new_instancemethod(_BRepFeat.BRepFeat_MakeCylindricalHole_PerformUntilEnd, None, BRepFeat_MakeCylindricalHole)
BRepFeat_MakeCylindricalHole.Status = new_instancemethod(_BRepFeat.BRepFeat_MakeCylindricalHole_Status, None, BRepFeat_MakeCylindricalHole)
BRepFeat_MakeCylindricalHole_swigregister = _BRepFeat.BRepFeat_MakeCylindricalHole_swigregister
BRepFeat_MakeCylindricalHole_swigregister(BRepFeat_MakeCylindricalHole)

class BRepFeat_MakeDPrism(BRepFeat_Form):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def Add(self, *args) -> "void":
        """
        * Indicates that the edge <E> will slide on the face <OnFace>. Raises ConstructionError if the face does not belong to the basis shape, or the edge to the prismed shape.
        	:param E:
        	:type E: TopoDS_Edge
        	:param OnFace:
        	:type OnFace: TopoDS_Face
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeDPrism_Add(self, *args)


    def __init__(self, *args):
        """
        * A face Pbase is selected in the shape Sbase to serve as the basis for the draft prism. The draft will be defined by the angle Angle and Fuse offers a choice between: - removing matter with a Boolean cut using the setting 0 - adding matter with Boolean fusion using the setting 1. The sketch face Skface serves to determine the type of operation. If it is inside the basis shape, a local operation such as glueing can be performed. Initializes the draft prism class
        	:param Sbase:
        	:type Sbase: TopoDS_Shape
        	:param Pbase:
        	:type Pbase: TopoDS_Face
        	:param Skface:
        	:type Skface: TopoDS_Face
        	:param Angle:
        	:type Angle: float
        	:param Fuse:
        	:type Fuse: int
        	:param Modify:
        	:type Modify: bool
        	:rtype: None
        :rtype: None
        """
        _BRepFeat.BRepFeat_MakeDPrism_swiginit(self, _BRepFeat.new_BRepFeat_MakeDPrism(*args))

    def BossEdges(self, *args) -> "void":
        """
        * Determination of TopEdges and LatEdges. sig = 1 -> TopEdges = FirstShape of the DPrism sig = 2 -> TOpEdges = LastShape of the DPrism
        	:param sig:
        	:type sig: int
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeDPrism_BossEdges(self, *args)


    def Init(self, *args) -> "void":
        """
        * Initializes this algorithm for building draft prisms along surfaces. A face Pbase is selected in the basis shape Sbase to serve as the basis from the draft prism. The draft will be defined by the angle Angle and Fuse offers a choice between: - removing matter with a Boolean cut using the setting 0 - adding matter with Boolean fusion using the setting 1. The sketch face Skface serves to determine the type of operation. If it is inside the basis shape, a local operation such as glueing can be performed.
        	:param Sbase:
        	:type Sbase: TopoDS_Shape
        	:param Pbase:
        	:type Pbase: TopoDS_Face
        	:param Skface:
        	:type Skface: TopoDS_Face
        	:param Angle:
        	:type Angle: float
        	:param Fuse:
        	:type Fuse: int
        	:param Modify:
        	:type Modify: bool
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeDPrism_Init(self, *args)


    def LatEdges(self, *args) -> "TopTools_ListOfShape const &":
        """
        * Returns the list of TopoDS Edges of the bottom of the boss.
        	:rtype: TopTools_ListOfShape
        """
        return _BRepFeat.BRepFeat_MakeDPrism_LatEdges(self, *args)


    def Perform(self, *args) -> "void":
        """
        :param Height:
        	:type Height: float
        	:rtype: None
        :param Until:
        	:type Until: TopoDS_Shape
        	:rtype: None
        * Assigns one of the following semantics - to a height Height - to a face Until - from a face From to a height Until. Reconstructs the feature topologically according to the semantic option chosen.
        	:param From:
        	:type From: TopoDS_Shape
        	:param Until:
        	:type Until: TopoDS_Shape
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeDPrism_Perform(self, *args)


    def PerformFromEnd(self, *args) -> "void":
        """
        * Realizes a semi-infinite prism, limited by the face Funtil.
        	:param FUntil:
        	:type FUntil: TopoDS_Shape
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeDPrism_PerformFromEnd(self, *args)


    def PerformThruAll(self, *args) -> "void":
        """
        * Builds an infinite prism. The infinite descendants will not be kept in the result.
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeDPrism_PerformThruAll(self, *args)


    def PerformUntilEnd(self, *args) -> "void":
        """
        * Realizes a semi-infinite prism, limited by the position of the prism base.
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeDPrism_PerformUntilEnd(self, *args)


    def PerformUntilHeight(self, *args) -> "void":
        """
        * Assigns both a limiting shape, Until from TopoDS_Shape, and a height, Height at which to stop generation of the prism feature.
        	:param Until:
        	:type Until: TopoDS_Shape
        	:param Height:
        	:type Height: float
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeDPrism_PerformUntilHeight(self, *args)


    def TopEdges(self, *args) -> "TopTools_ListOfShape const &":
        """
        * Returns the list of TopoDS Edges of the top of the boss.
        	:rtype: TopTools_ListOfShape
        """
        return _BRepFeat.BRepFeat_MakeDPrism_TopEdges(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _BRepFeat.delete_BRepFeat_MakeDPrism
BRepFeat_MakeDPrism.Add = new_instancemethod(_BRepFeat.BRepFeat_MakeDPrism_Add, None, BRepFeat_MakeDPrism)
BRepFeat_MakeDPrism.BossEdges = new_instancemethod(_BRepFeat.BRepFeat_MakeDPrism_BossEdges, None, BRepFeat_MakeDPrism)
BRepFeat_MakeDPrism.Init = new_instancemethod(_BRepFeat.BRepFeat_MakeDPrism_Init, None, BRepFeat_MakeDPrism)
BRepFeat_MakeDPrism.LatEdges = new_instancemethod(_BRepFeat.BRepFeat_MakeDPrism_LatEdges, None, BRepFeat_MakeDPrism)
BRepFeat_MakeDPrism.Perform = new_instancemethod(_BRepFeat.BRepFeat_MakeDPrism_Perform, None, BRepFeat_MakeDPrism)
BRepFeat_MakeDPrism.PerformFromEnd = new_instancemethod(_BRepFeat.BRepFeat_MakeDPrism_PerformFromEnd, None, BRepFeat_MakeDPrism)
BRepFeat_MakeDPrism.PerformThruAll = new_instancemethod(_BRepFeat.BRepFeat_MakeDPrism_PerformThruAll, None, BRepFeat_MakeDPrism)
BRepFeat_MakeDPrism.PerformUntilEnd = new_instancemethod(_BRepFeat.BRepFeat_MakeDPrism_PerformUntilEnd, None, BRepFeat_MakeDPrism)
BRepFeat_MakeDPrism.PerformUntilHeight = new_instancemethod(_BRepFeat.BRepFeat_MakeDPrism_PerformUntilHeight, None, BRepFeat_MakeDPrism)
BRepFeat_MakeDPrism.TopEdges = new_instancemethod(_BRepFeat.BRepFeat_MakeDPrism_TopEdges, None, BRepFeat_MakeDPrism)
BRepFeat_MakeDPrism_swigregister = _BRepFeat.BRepFeat_MakeDPrism_swigregister
BRepFeat_MakeDPrism_swigregister(BRepFeat_MakeDPrism)

class BRepFeat_MakeLinearForm(BRepFeat_RibSlot):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def Add(self, *args) -> "void":
        """
        * Indicates that the edge <E> will slide on the face <OnFace>. Raises ConstructionError if the face does not belong to the basis shape, or the edge to the prismed shape.
        	:param E:
        	:type E: TopoDS_Edge
        	:param OnFace:
        	:type OnFace: TopoDS_Face
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeLinearForm_Add(self, *args)


    def __init__(self, *args):
        """
        * initializes the linear form class
        	:rtype: None
        * contour W, a shape Sbase and a plane P are initialized to serve as the basic elements in the construction of the rib or groove. Direction and Direction1 give The vectors for defining the direction(s) in which thickness will be built up. Fuse offers a choice between: - removing matter with a Boolean cut using the setting 0 in case of the groove - adding matter with Boolean fusion using the setting 1 in case of the rib.
        	:param Sbase:
        	:type Sbase: TopoDS_Shape
        	:param W:
        	:type W: TopoDS_Wire
        	:param P:
        	:type P: Geom_Plane
        	:param Direction:
        	:type Direction: gp_Vec
        	:param Direction1:
        	:type Direction1: gp_Vec
        	:param Fuse:
        	:type Fuse: int
        	:param Modify:
        	:type Modify: bool
        	:rtype: None
        """
        _BRepFeat.BRepFeat_MakeLinearForm_swiginit(self, _BRepFeat.new_BRepFeat_MakeLinearForm(*args))

    def Init(self, *args) -> "void":
        """
        * Initializes this construction algorithm. A contour W, a shape Sbase and a plane P are initialized to serve as the basic elements in the construction of the rib or groove. The vectors for defining the direction(s) in which thickness will be built up are given by Direction and Direction1. Fuse offers a choice between: - removing matter with a Boolean cut using the setting 0 in case of the groove - adding matter with Boolean fusion using the setting 1 in case of the rib.
        	:param Sbase:
        	:type Sbase: TopoDS_Shape
        	:param W:
        	:type W: TopoDS_Wire
        	:param P:
        	:type P: Geom_Plane
        	:param Direction:
        	:type Direction: gp_Vec
        	:param Direction1:
        	:type Direction1: gp_Vec
        	:param Fuse:
        	:type Fuse: int
        	:param Modify:
        	:type Modify: bool
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeLinearForm_Init(self, *args)


    def Perform(self, *args) -> "void":
        """
        * Performs a prism from the wire to the plane along the basis shape Sbase. Reconstructs the feature topologically.
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeLinearForm_Perform(self, *args)


    def Propagate(self, *args) -> "Standard_Boolean":
        """
        :param L:
        	:type L: TopTools_ListOfShape
        	:param F:
        	:type F: TopoDS_Face
        	:param FPoint:
        	:type FPoint: gp_Pnt
        	:param LPoint:
        	:type LPoint: gp_Pnt
        	:param falseside:
        	:type falseside: bool
        	:rtype: bool
        """
        return _BRepFeat.BRepFeat_MakeLinearForm_Propagate(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _BRepFeat.delete_BRepFeat_MakeLinearForm
BRepFeat_MakeLinearForm.Add = new_instancemethod(_BRepFeat.BRepFeat_MakeLinearForm_Add, None, BRepFeat_MakeLinearForm)
BRepFeat_MakeLinearForm.Init = new_instancemethod(_BRepFeat.BRepFeat_MakeLinearForm_Init, None, BRepFeat_MakeLinearForm)
BRepFeat_MakeLinearForm.Perform = new_instancemethod(_BRepFeat.BRepFeat_MakeLinearForm_Perform, None, BRepFeat_MakeLinearForm)
BRepFeat_MakeLinearForm.Propagate = new_instancemethod(_BRepFeat.BRepFeat_MakeLinearForm_Propagate, None, BRepFeat_MakeLinearForm)
BRepFeat_MakeLinearForm_swigregister = _BRepFeat.BRepFeat_MakeLinearForm_swigregister
BRepFeat_MakeLinearForm_swigregister(BRepFeat_MakeLinearForm)

class BRepFeat_MakePipe(BRepFeat_Form):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def Add(self, *args) -> "void":
        """
        * Indicates that the edge <E> will slide on the face <OnFace>. Raises ConstructionError if the face does not belong to the basis shape, or the edge to the prismed shape.
        	:param E:
        	:type E: TopoDS_Edge
        	:param OnFace:
        	:type OnFace: TopoDS_Face
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakePipe_Add(self, *args)


    def __init__(self, *args):
        """
        * initializes the pipe class.
        	:rtype: None
        * A face Pbase is selected in the shape Sbase to serve as the basis for the pipe. It will be defined by the wire Spine. Fuse offers a choice between: - removing matter with a Boolean cut using the setting 0 - adding matter with Boolean fusion using the setting 1. The sketch face Skface serves to determine the type of operation. If it is inside the basis shape, a local operation such as glueing can be performed.
        	:param Sbase:
        	:type Sbase: TopoDS_Shape
        	:param Pbase:
        	:type Pbase: TopoDS_Shape
        	:param Skface:
        	:type Skface: TopoDS_Face
        	:param Spine:
        	:type Spine: TopoDS_Wire
        	:param Fuse:
        	:type Fuse: int
        	:param Modify:
        	:type Modify: bool
        	:rtype: None
        """
        _BRepFeat.BRepFeat_MakePipe_swiginit(self, _BRepFeat.new_BRepFeat_MakePipe(*args))

    def Init(self, *args) -> "void":
        """
        * Initializes this algorithm for adding pipes to shapes. A face Pbase is selected in the shape Sbase to serve as the basis for the pipe. It will be defined by the wire Spine. Fuse offers a choice between: - removing matter with a Boolean cut using the setting 0 - adding matter with Boolean fusion using the setting 1. The sketch face Skface serves to determine the type of operation. If it is inside the basis shape, a local operation such as glueing can be performed.
        	:param Sbase:
        	:type Sbase: TopoDS_Shape
        	:param Pbase:
        	:type Pbase: TopoDS_Shape
        	:param Skface:
        	:type Skface: TopoDS_Face
        	:param Spine:
        	:type Spine: TopoDS_Wire
        	:param Fuse:
        	:type Fuse: int
        	:param Modify:
        	:type Modify: bool
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakePipe_Init(self, *args)


    def Perform(self, *args) -> "void":
        """
        :rtype: None
        :param Until:
        	:type Until: TopoDS_Shape
        	:rtype: None
        * Assigns one of the following semantics - to a face Until - from a face From to a height Until. Reconstructs the feature topologically according to the semantic option chosen.
        	:param From:
        	:type From: TopoDS_Shape
        	:param Until:
        	:type Until: TopoDS_Shape
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakePipe_Perform(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _BRepFeat.delete_BRepFeat_MakePipe
BRepFeat_MakePipe.Add = new_instancemethod(_BRepFeat.BRepFeat_MakePipe_Add, None, BRepFeat_MakePipe)
BRepFeat_MakePipe.Init = new_instancemethod(_BRepFeat.BRepFeat_MakePipe_Init, None, BRepFeat_MakePipe)
BRepFeat_MakePipe.Perform = new_instancemethod(_BRepFeat.BRepFeat_MakePipe_Perform, None, BRepFeat_MakePipe)
BRepFeat_MakePipe_swigregister = _BRepFeat.BRepFeat_MakePipe_swigregister
BRepFeat_MakePipe_swigregister(BRepFeat_MakePipe)

class BRepFeat_MakePrism(BRepFeat_Form):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def Add(self, *args) -> "void":
        """
        * Indicates that the edge <E> will slide on the face <OnFace>. Raises ConstructionError if the face does not belong to the basis shape, or the edge to the prismed shape.
        	:param E:
        	:type E: TopoDS_Edge
        	:param OnFace:
        	:type OnFace: TopoDS_Face
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakePrism_Add(self, *args)


    def __init__(self, *args):
        """
        * Builds a prism by projecting a wire along the face of a shape. Initializes the prism class.
        	:rtype: None
        * Builds a prism by projecting a wire along the face of a shape. a face Pbase is selected in the shape Sbase to serve as the basis for the prism. The orientation of the prism will be defined by the vector Direction. Fuse offers a choice between: - removing matter with a Boolean cut using the setting 0 - adding matter with Boolean fusion using the setting 1. The sketch face Skface serves to determine the type of operation. If it is inside the basis shape, a local operation such as glueing can be performed. Exceptions Standard_ConstructionError if the face does not belong to the basis or the prism shape.
        	:param Sbase:
        	:type Sbase: TopoDS_Shape
        	:param Pbase:
        	:type Pbase: TopoDS_Shape
        	:param Skface:
        	:type Skface: TopoDS_Face
        	:param Direction:
        	:type Direction: gp_Dir
        	:param Fuse:
        	:type Fuse: int
        	:param Modify:
        	:type Modify: bool
        	:rtype: None
        """
        _BRepFeat.BRepFeat_MakePrism_swiginit(self, _BRepFeat.new_BRepFeat_MakePrism(*args))

    def Init(self, *args) -> "void":
        """
        * Initializes this algorithm for building prisms along surfaces. A face Pbase is selected in the shape Sbase to serve as the basis for the prism. The orientation of the prism will be defined by the vector Direction. Fuse offers a choice between: - removing matter with a Boolean cut using the setting 0 - adding matter with Boolean fusion using the setting 1. The sketch face Skface serves to determine the type of operation. If it is inside the basis shape, a local operation such as glueing can be performed.
        	:param Sbase:
        	:type Sbase: TopoDS_Shape
        	:param Pbase:
        	:type Pbase: TopoDS_Shape
        	:param Skface:
        	:type Skface: TopoDS_Face
        	:param Direction:
        	:type Direction: gp_Dir
        	:param Fuse:
        	:type Fuse: int
        	:param Modify:
        	:type Modify: bool
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakePrism_Init(self, *args)


    def Perform(self, *args) -> "void":
        """
        :param Length:
        	:type Length: float
        	:rtype: None
        :param Until:
        	:type Until: TopoDS_Shape
        	:rtype: None
        * Assigns one of the following semantics - to a height Length - to a face Until - from a face From to a height Until. Reconstructs the feature topologically according to the semantic option chosen.
        	:param From:
        	:type From: TopoDS_Shape
        	:param Until:
        	:type Until: TopoDS_Shape
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakePrism_Perform(self, *args)


    def PerformFromEnd(self, *args) -> "void":
        """
        * Realizes a semi-infinite prism, limited by the face Funtil.
        	:param FUntil:
        	:type FUntil: TopoDS_Shape
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakePrism_PerformFromEnd(self, *args)


    def PerformThruAll(self, *args) -> "void":
        """
        * Builds an infinite prism. The infinite descendants will not be kept in the result.
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakePrism_PerformThruAll(self, *args)


    def PerformUntilEnd(self, *args) -> "void":
        """
        * Realizes a semi-infinite prism, limited by the position of the prism base. All other faces extend infinitely.
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakePrism_PerformUntilEnd(self, *args)


    def PerformUntilHeight(self, *args) -> "void":
        """
        * Assigns both a limiting shape, Until from TopoDS_Shape, and a height, Length at which to stop generation of the prism feature.
        	:param Until:
        	:type Until: TopoDS_Shape
        	:param Length:
        	:type Length: float
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakePrism_PerformUntilHeight(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _BRepFeat.delete_BRepFeat_MakePrism
BRepFeat_MakePrism.Add = new_instancemethod(_BRepFeat.BRepFeat_MakePrism_Add, None, BRepFeat_MakePrism)
BRepFeat_MakePrism.Init = new_instancemethod(_BRepFeat.BRepFeat_MakePrism_Init, None, BRepFeat_MakePrism)
BRepFeat_MakePrism.Perform = new_instancemethod(_BRepFeat.BRepFeat_MakePrism_Perform, None, BRepFeat_MakePrism)
BRepFeat_MakePrism.PerformFromEnd = new_instancemethod(_BRepFeat.BRepFeat_MakePrism_PerformFromEnd, None, BRepFeat_MakePrism)
BRepFeat_MakePrism.PerformThruAll = new_instancemethod(_BRepFeat.BRepFeat_MakePrism_PerformThruAll, None, BRepFeat_MakePrism)
BRepFeat_MakePrism.PerformUntilEnd = new_instancemethod(_BRepFeat.BRepFeat_MakePrism_PerformUntilEnd, None, BRepFeat_MakePrism)
BRepFeat_MakePrism.PerformUntilHeight = new_instancemethod(_BRepFeat.BRepFeat_MakePrism_PerformUntilHeight, None, BRepFeat_MakePrism)
BRepFeat_MakePrism_swigregister = _BRepFeat.BRepFeat_MakePrism_swigregister
BRepFeat_MakePrism_swigregister(BRepFeat_MakePrism)

class BRepFeat_MakeRevol(BRepFeat_Form):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def Add(self, *args) -> "void":
        """
        * Indicates that the edge <E> will slide on the face <OnFace>. Raises ConstructionError if the face does not belong to the basis shape, or the edge to the prismed shape.
        	:param E:
        	:type E: TopoDS_Edge
        	:param OnFace:
        	:type OnFace: TopoDS_Face
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeRevol_Add(self, *args)


    def __init__(self, *args):
        """
        * initializes the revolved shell class.
        	:rtype: None
        * a face Pbase is selected in the shape Sbase to serve as the basis for the revolved shell. The revolution will be defined by the axis Axis and Fuse offers a choice between: - removing matter with a Boolean cut using the setting 0 - adding matter with Boolean fusion using the setting 1. The sketch face Skface serves to determine the type of operation. If it is inside the basis shape, a local operation such as glueing can be performed.
        	:param Sbase:
        	:type Sbase: TopoDS_Shape
        	:param Pbase:
        	:type Pbase: TopoDS_Shape
        	:param Skface:
        	:type Skface: TopoDS_Face
        	:param Axis:
        	:type Axis: gp_Ax1
        	:param Fuse:
        	:type Fuse: int
        	:param Modify:
        	:type Modify: bool
        	:rtype: None
        """
        _BRepFeat.BRepFeat_MakeRevol_swiginit(self, _BRepFeat.new_BRepFeat_MakeRevol(*args))

    def Init(self, *args) -> "void":
        """
        :param Sbase:
        	:type Sbase: TopoDS_Shape
        	:param Pbase:
        	:type Pbase: TopoDS_Shape
        	:param Skface:
        	:type Skface: TopoDS_Face
        	:param Axis:
        	:type Axis: gp_Ax1
        	:param Fuse:
        	:type Fuse: int
        	:param Modify:
        	:type Modify: bool
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeRevol_Init(self, *args)


    def Perform(self, *args) -> "void":
        """
        :param Angle:
        	:type Angle: float
        	:rtype: None
        :param Until:
        	:type Until: TopoDS_Shape
        	:rtype: None
        * Reconstructs the feature topologically.
        	:param From:
        	:type From: TopoDS_Shape
        	:param Until:
        	:type Until: TopoDS_Shape
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeRevol_Perform(self, *args)


    def PerformThruAll(self, *args) -> "void":
        """
        * Builds an infinite shell. The infinite descendants will not be kept in the result.
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeRevol_PerformThruAll(self, *args)


    def PerformUntilAngle(self, *args) -> "void":
        """
        * Assigns both a limiting shape, Until from TopoDS_Shape, and an angle, Angle at which to stop generation of the revolved shell feature.
        	:param Until:
        	:type Until: TopoDS_Shape
        	:param Angle:
        	:type Angle: float
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeRevol_PerformUntilAngle(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _BRepFeat.delete_BRepFeat_MakeRevol
BRepFeat_MakeRevol.Add = new_instancemethod(_BRepFeat.BRepFeat_MakeRevol_Add, None, BRepFeat_MakeRevol)
BRepFeat_MakeRevol.Init = new_instancemethod(_BRepFeat.BRepFeat_MakeRevol_Init, None, BRepFeat_MakeRevol)
BRepFeat_MakeRevol.Perform = new_instancemethod(_BRepFeat.BRepFeat_MakeRevol_Perform, None, BRepFeat_MakeRevol)
BRepFeat_MakeRevol.PerformThruAll = new_instancemethod(_BRepFeat.BRepFeat_MakeRevol_PerformThruAll, None, BRepFeat_MakeRevol)
BRepFeat_MakeRevol.PerformUntilAngle = new_instancemethod(_BRepFeat.BRepFeat_MakeRevol_PerformUntilAngle, None, BRepFeat_MakeRevol)
BRepFeat_MakeRevol_swigregister = _BRepFeat.BRepFeat_MakeRevol_swigregister
BRepFeat_MakeRevol_swigregister(BRepFeat_MakeRevol)

class BRepFeat_MakeRevolutionForm(BRepFeat_RibSlot):
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr

    def Add(self, *args) -> "void":
        """
        * Indicates that the edge <E> will slide on the face <OnFace>. Raises ConstructionError if the face does not belong to the basis shape, or the edge to the prismed shape.
        	:param E:
        	:type E: TopoDS_Edge
        	:param OnFace:
        	:type OnFace: TopoDS_Face
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeRevolutionForm_Add(self, *args)


    def __init__(self, *args):
        """
        * initializes the linear form class.
        	:rtype: None
        * a contour W, a shape Sbase and a plane P are initialized to serve as the basic elements in the construction of the rib or groove. The axis Axis of the revolved surface in the basis shape defines the feature's axis of revolution. Height1 and Height2 may be used as limits to the construction of the feature. Fuse offers a choice between: - removing matter with a Boolean cut using the setting 0 in case of the groove - adding matter with Boolean fusion using the setting 1 in case of the rib.
        	:param Sbase:
        	:type Sbase: TopoDS_Shape
        	:param W:
        	:type W: TopoDS_Wire
        	:param Plane:
        	:type Plane: Geom_Plane
        	:param Axis:
        	:type Axis: gp_Ax1
        	:param Height1:
        	:type Height1: float
        	:param Height2:
        	:type Height2: float
        	:param Fuse:
        	:type Fuse: int
        	:param Sliding:
        	:type Sliding: bool
        	:rtype: None
        """
        _BRepFeat.BRepFeat_MakeRevolutionForm_swiginit(self, _BRepFeat.new_BRepFeat_MakeRevolutionForm(*args))

    def Init(self, *args) -> "void":
        """
        * Initializes this construction algorithm A contour W, a shape Sbase and a plane P are initialized to serve as the basic elements in the construction of the rib or groove. The axis Axis of the revolved surface in the basis shape defines the feature's axis of revolution. Height1 and Height2 may be used as limits to the construction of the feature. Fuse offers a choice between: - removing matter with a Boolean cut using the setting 0 in case of the groove - adding matter with Boolean fusion using the setting 1 in case of the rib.
        	:param Sbase:
        	:type Sbase: TopoDS_Shape
        	:param W:
        	:type W: TopoDS_Wire
        	:param Plane:
        	:type Plane: Geom_Plane
        	:param Axis:
        	:type Axis: gp_Ax1
        	:param Height1:
        	:type Height1: float
        	:param Height2:
        	:type Height2: float
        	:param Fuse:
        	:type Fuse: int
        	:param Sliding:
        	:type Sliding: bool
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeRevolutionForm_Init(self, *args)


    def Perform(self, *args) -> "void":
        """
        * Performs a prism from the wire to the plane along the basis shape S. Reconstructs the feature topologically.
        	:rtype: None
        """
        return _BRepFeat.BRepFeat_MakeRevolutionForm_Perform(self, *args)


    def Propagate(self, *args) -> "Standard_Boolean":
        """
        :param L:
        	:type L: TopTools_ListOfShape
        	:param F:
        	:type F: TopoDS_Face
        	:param FPoint:
        	:type FPoint: gp_Pnt
        	:param LPoint:
        	:type LPoint: gp_Pnt
        	:param falseside:
        	:type falseside: bool
        	:rtype: bool
        """
        return _BRepFeat.BRepFeat_MakeRevolutionForm_Propagate(self, *args)


    __repr__ = _dumps_object

    __swig_destroy__ = _BRepFeat.delete_BRepFeat_MakeRevolutionForm
BRepFeat_MakeRevolutionForm.Add = new_instancemethod(_BRepFeat.BRepFeat_MakeRevolutionForm_Add, None, BRepFeat_MakeRevolutionForm)
BRepFeat_MakeRevolutionForm.Init = new_instancemethod(_BRepFeat.BRepFeat_MakeRevolutionForm_Init, None, BRepFeat_MakeRevolutionForm)
BRepFeat_MakeRevolutionForm.Perform = new_instancemethod(_BRepFeat.BRepFeat_MakeRevolutionForm_Perform, None, BRepFeat_MakeRevolutionForm)
BRepFeat_MakeRevolutionForm.Propagate = new_instancemethod(_BRepFeat.BRepFeat_MakeRevolutionForm_Propagate, None, BRepFeat_MakeRevolutionForm)
BRepFeat_MakeRevolutionForm_swigregister = _BRepFeat.BRepFeat_MakeRevolutionForm_swigregister
BRepFeat_MakeRevolutionForm_swigregister(BRepFeat_MakeRevolutionForm)



